version: "3.4"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - "2181:2181"
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka0: &broker-default
    # https://docs.confluent.io/current/installation/versions-interoperability.html#cp-and-apache-ak-compatibility
    # version maps to kafka 2.6.0
    image: confluentinc/cp-kafka:6.0.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment: &default-broker-env
      KAFKA_BROKER_ID: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "2"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "2"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: "INTERNAL://kafka0:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka0:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
  kafka1:
    <<: *broker-default
    ports:
      - "9093:9093"
    environment:
      <<: *default-broker-env
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: "INTERNAL://kafka1:29093,EXTERNAL://:9093"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka1:29093,EXTERNAL://localhost:9093"
  kafka-cli:
    image: frser/kafka-cli:2.6.0
    environment:
      BOOTSTRAP_SERVER: kafka0:29092
      CREATE_TOPICS: >-
        readings:2:2,
        filtered-readings:2:2,
        filter-condition:1:2:compact,
    depends_on:
      - kafka0
      - kafka1
  filter-build-cache:
    build:
      context: .
      target: builder
  filter:
    build:
      context: .
    env_file:
      - bootstrap.env
    environment:
      BOOTSTRAP_SERVERS: "kafka0:29092,kafka1:29093"
    depends_on:
      - kafka0
      - kafka1
